// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tenets.Identity.Data.Context;

namespace Tenets.Identity.Data.Migrations
{
    [DbContext(typeof(IdentityContext))]
    [Migration("20190928082327_modiyidentity")]
    partial class modiyidentity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Tenets.Identity.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime?>("LastAccessed")
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c21c91c0-5c2f-45cc-ab6d-1d256538a5ee"),
                            IsDeleted = false,
                            LastAccessed = new DateTime(2019, 9, 28, 10, 23, 26, 150, DateTimeKind.Local).AddTicks(1251),
                            Name = "SuperAdmin"
                        },
                        new
                        {
                            Id = new Guid("c31c91c0-5c2f-45cc-ab6d-1d256538a6ee"),
                            IsDeleted = false,
                            LastAccessed = new DateTime(2019, 9, 28, 10, 23, 26, 150, DateTimeKind.Local).AddTicks(1838),
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("c41c91c0-5c2f-45cc-ab6d-1d256538a7ee"),
                            IsDeleted = false,
                            LastAccessed = new DateTime(2019, 9, 28, 10, 23, 26, 150, DateTimeKind.Local).AddTicks(1857),
                            Name = "User"
                        });
                });

            modelBuilder.Entity("Tenets.Identity.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime?>("LastAccessed")
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("Password");

                    b.Property<string>("PhoneNumber");

                    b.Property<Guid>("RoleId");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c21c91c0-5c2f-45cc-ab6d-1d256538a4ee"),
                            Email = "admin@A3n.com",
                            IsDeleted = false,
                            LastAccessed = new DateTime(2019, 9, 28, 10, 23, 26, 42, DateTimeKind.Local).AddTicks(2591),
                            Password = "ADODTSgerU6FrBy/sNxk/imohjGADqV/AMjYYLw/jssO2gQIY6sC9prIFhby6sgdPQ==",
                            PhoneNumber = "+9",
                            RoleId = new Guid("c21c91c0-5c2f-45cc-ab6d-1d256538a5ee"),
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("Tenets.Identity.Entities.User", b =>
                {
                    b.HasOne("Tenets.Identity.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
